### ISSUE TITLE
T-Test 

### ISSUE THREAD

**Issue by TalitaGroetzinger** [pmsprenger/dh_2017_analysingdata_finalproject#29]
Apparently, t-test shows some weird results. Can everyone please run the code and check the result? I got: 
t-value = -15.2539633087
p-value = 4.76447620162e-52

**Comment by MarcoPost1987** [comment]
This issue has been closed, a we think that it is quite likely that the computer has problems with coping with minute floating point notations. Floating points as they are stored in the computer's memory are approximations of fractions, after all, not real fractions themselves.
